### PR TITLE
adding ability to use tar_quarto and setup an initial qmd document

### PR DESCRIPTION
**Pull request by rmflight**

### CODE REVIEW

**Comment by rmflight** [comment]
Hey @MilesMcBain , any thing I can do to help move this along? 
If it's any help, I've already been using this on my own `tflow` projects.

If you don't think it warrants being listed as a contributor, that's also fine.

**Comment by MilesMcBain** [comment]
I do actually. Add yourself as ctb?

Sorry to leave this one hanging. It's next on the pile, probably this
evening.

**Comment by rmflight** [comment]
I actually did add myself as ctb in the DESCRIPTION

https://github.com/MilesMcBain/tflow/pull/21/files#diff-9cc358405149db607ff830a16f0b4b21f7366e3c99ec00d52800acebe21b231cR8

**Comment by MilesMcBain** [comment]
Excellent, everything is covered off here. A+ PR sir. Thankyou.

**Pull request merged**
